/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './hint.component';
import * as i3 from './hint.service';
const styles_HintComponent:any[] = ([] as any[]);
export const RenderType_HintComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_HintComponent,data:{}});
function View_HintComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),0,'div',[['class',
      'hint-overlay']],(null as any),[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    var _co:any = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.dismiss()) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any)))],(null as any),(null as any));
}
export function View_HintComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),
      View_HintComponent_1)),i0.ɵdid(1,16384,(null as any),0,i1.NgIf,[i0.ViewContainerRef,
      i0.TemplateRef],{ngIf:[0,'ngIf']},(null as any))],(_ck,_v) => {
    var _co:i2.HintComponent = _v.component;
    const currVal_0:any = _co.show;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_HintComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'tour-overlay',
      ([] as any[]),(null as any),(null as any),(null as any),View_HintComponent_0,
      RenderType_HintComponent)),i0.ɵdid(1,49152,(null as any),0,i2.HintComponent,
      [i3.HintService],(null as any),(null as any))],(null as any),(null as any));
}
export const HintComponentNgFactory:i0.ComponentFactory<i2.HintComponent> = i0.ɵccf('tour-overlay',
    i2.HintComponent,View_HintComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21pcmF4ZXMvRGV2L21tLWhpbnQvc3JjL2hpbnQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL21pcmF4ZXMvRGV2L21tLWhpbnQvc3JjL2hpbnQuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvbWlyYXhlcy9EZXYvbW0taGludC9zcmMvaGludC5jb21wb25lbnQudHMuSGludENvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvbWlyYXhlcy9EZXYvbW0taGludC9zcmMvaGludC5jb21wb25lbnQudHMuSGludENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJoaW50LW92ZXJsYXlcIiAqbmdJZj1cInNob3dcIiAoY2xpY2spPVwiZGlzbWlzcygpXCI+PC9kaXY+IiwiPHRvdXItb3ZlcmxheT48L3RvdXItb3ZlcmxheT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7SUFBQTtJQUFBO0lBQXVDO01BQUE7TUFBQTtJQUFBO0lBQXZDO0VBQUE7OztvQkFBQTtNQUFBLDhCQUFBO29CQUFBOztJQUEwQjtJQUExQixXQUEwQixTQUExQjs7OztvQkNBQTtNQUFBOzhCQUFBLFVBQUE7TUFBQTs7OyJ9
